import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{...cors,"Content-Type":"application/json"}});
const url=Deno.env.get("SUPABASE_URL")!, key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(url,key);
async function auth(req:Request){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))throw new Error("Missing authorization");const token=h.slice(7);const {data:{user},error}=await admin.auth.getUser(token);if(error||!user)throw new Error("Unauthorized");const {data:profile}=await admin.from("admin_profiles").select("user_id,full_name,role,active").eq("user_id",user.id).single();if(!profile?.active)throw new Error("Active admin profile required");return {user,profile};}
function render(t:string,v:Record<string,string>){return t.replace(/{{(\w+)}}/g,(_,k)=>v[k]??"");}
async function providerConfigured(){return Boolean(Deno.env.get("WHATSAPP_API_TOKEN")&&Deno.env.get("WHATSAPP_PHONE_NUMBER_ID"))}
async function sendWhatsApp(to:string,body:string){const token=Deno.env.get("WHATSAPP_API_TOKEN"),phoneId=Deno.env.get("WHATSAPP_PHONE_NUMBER_ID"),version=Deno.env.get("WHATSAPP_API_VERSION")||"v23.0";if(!token||!phoneId)return {configured:false};const r=await fetch(`https://graph.facebook.com/${version}/${phoneId}/messages`,{method:"POST",headers:{"Authorization":`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:typePhone(to),type:"text",text:{preview_url:false,body}})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||"WhatsApp provider failed");return {configured:true,id:j.messages?.[0]?.id||null};}
function typePhone(v:string){return String(v||"").replace(/[^0-9]/g,"")}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const {user,profile}=await auth(req);const u=new URL(req.url),action=u.searchParams.get("action")||"dashboard";if(action==="me")return json({profile});
if(action==="bootstrap"){const [a,b,c,d]=await Promise.all([admin.from("emergency_incident_types").select("*").eq("active",true).order("name"),admin.from("emergency_message_templates").select("*").eq("active",true).order("name"),admin.from("emergency_contacts").select("*").eq("active",true).order("priority").order("full_name"),admin.from("emergency_contact_groups").select("*").eq("active",true).order("name")]);return json({types:a.data||[],templates:b.data||[],contacts:c.data||[],groups:d.data||[],provider_configured:await providerConfigured()});}
if(action==="dashboard"){const start=new Date();start.setHours(0,0,0,0);const [inc,not,ack]=await Promise.all([admin.from("emergency_incidents").select("*").order("created_at",{ascending:false}).limit(30),admin.from("emergency_notifications").select("id,status,created_at:queued_at",{count:"exact"}).gte("queued_at",start.toISOString()),admin.from("emergency_incident_recipients").select("id,emergency_incidents!inner(status),emergency_acknowledgements!left(id)",{count:"exact"}).in("emergency_incidents.status",["ACTIVE","MONITORING"])]);const active=(inc.data||[]).filter(x=>["ACTIVE","MONITORING"].includes(x.status));return json({stats:{active:active.length,urgent:active.filter(x=>x.severity==="URGENT").length,notifications_today:not.count||0,pending_ack:Math.max(0,(ack.data||[]).filter((x:any)=>!x.emergency_acknowledgements).length)},incidents:inc.data||[],provider_configured:await providerConfigured()});}
if(action==="incident_detail"){const id=u.searchParams.get("incident_id");if(!id)throw new Error("incident_id required");const [i,n,up]=await Promise.all([admin.from("emergency_incidents").select("*,emergency_incident_types(name)").eq("id",id).single(),admin.from("emergency_notifications").select("*,emergency_incident_recipients(contact_id,emergency_contacts(full_name))").eq("incident_id",id).order("queued_at"),admin.from("emergency_incident_updates").select("*").eq("incident_id",id).order("created_at",{ascending:true})]);const notifications=(n.data||[]).map((x:any)=>({id:x.id,channel:x.channel,status:x.status,name:x.emergency_incident_recipients?.emergency_contacts?.full_name||"Unknown"}));return json({incident:i.data,notifications,updates:up.data||[]});}
if(action==="create_incident"&&req.method==="POST"){const b=await req.json();if(!b.title||!b.description||!b.contact_ids?.length)throw new Error("Title, message and recipients are required");const {data:incident,error}=await admin.from("emergency_incidents").insert({incident_type_id:b.incident_type_id||null,severity:b.severity||"URGENT",title:b.title,location:b.location||null,description:b.description,status:"ACTIVE",test_mode:b.test_mode!==false,created_by:user.id}).select().single();if(error)throw error;const rows=b.contact_ids.map((contact_id:string)=>({incident_id:incident.id,contact_id}));const {data:recips,error:re}=await admin.from("emergency_incident_recipients").insert(rows).select("id,contact_id,emergency_contacts(*)");if(re)throw re;await admin.from("emergency_incident_updates").insert({incident_id:incident.id,status:"ACTIVE",title:"Incident Created",message:b.description,created_by:user.id});const channels:any[]=[];for(const r of recips||[]){const c=r.emergency_contacts;const list=[];if(c?.whatsapp_number)list.push("WHATSAPP");if(c?.phone_number)list.push("SMS");if(c?.email)list.push("EMAIL");for(const channel of list){const {data:n}=await admin.from("emergency_notifications").insert({incident_id:incident.id,recipient_id:r.id,channel,status:"QUEUED"}).select().single();if(n)channels.push({n,c,channel});}}
let sent=0;for(const x of channels.filter(x=>x.channel==="WHATSAPP")){try{const text=render(b.description,{location:b.location||"",title:b.title,time:new Date().toLocaleString("en-GB")});const p=await sendWhatsApp(x.c.whatsapp_number,text);if(p.configured){await admin.from("emergency_notifications").update({status:"SENT",provider_message_id:p.id,sent_at:new Date().toISOString()}).eq("id",x.n.id);sent++;}else{await admin.from("emergency_notifications").update({status:"PENDING",error_message:"WhatsApp provider not configured"}).eq("id",x.n.id);}}catch(e){await admin.from("emergency_notifications").update({status:"FAILED",error_message:String(e)}).eq("id",x.n.id);}}
await admin.from("audit_logs").insert({user_id:user.id,user_name:profile.full_name||user.email,module:"EMERGENCY",action:"CREATE_INCIDENT",target:incident.incident_id,description:`Created ${incident.severity} incident with ${b.contact_ids.length} recipients; test_mode=${incident.test_mode}`});return json({ok:true,incident,provider_configured:await providerConfigured(),sent});}
throw new Error("Unknown action");}catch(e){return json({error:e?.message||String(e)},400);}});
